FORMAT: 1A
HOST: https://api.planblick.com

# planBLICK API

The planBLICK API is a mostly json based API allowing consumers to 
build their completely own frontend for planBLICK applications.

# Group Account and login-management

IMPORTANT: The planBLICK API separates between "Account" and "Login" 
where "Account" (also frequently referred to as "consumer") is sort of a container for n logins. Think of an "Account"
as something a company has one, where logins is something each employee
of the company has one. During the account-registration, a corresponding 
login is created automatically.

## Registration [/registration]
### Starts registration process [POST]
planBLICK JS-Framework Example: [Codepen](https://codepen.io/planBLICK/pen/xxEEgjx)


+ Request

    + Headers

            content-type: application/json

    + Body
    
            {
                "username": "info@planblick.com",
                "password": "secretpassword"
            }

+ Response 200
    + Headers

            content-type: text/plain


    + Body
            
            {
                "taskid": "d87d4cc9-f88f-4260-be6e-4601baf71927"
            }

## Getting an apikey [/login]
### Perform Basic-Auth to obtain an apikey [GET]
planBLICK JS-Framework Examples: 

[Get apikey only](https://codepen.io/planBLICK/pen/NWRRpBV) if you only want to get the apikey in a pure programmatical way


[Perform login ](https://codepen.io/planBLICK/pen/ZEppegB) if you only want to create a form and let the framework do the heavy lifting. In this case your login-form need two input fields with id's "login" and "password". The function will pull out the data itself, do the request and set some cookies which are most commonly used with the api.


+ Request

    + Headers

            content-type: application/json
            Authorization: Basic ABC123

    + Body
    
+ Response 403

    + Headers

            content-type: application/json

    + Body

            {
                "message": "Invalid authentication credentials"
            }

+ Response 200

    + Headers

            content-type: application/json

    + Body

            {
                "apikey": "randomApiKey",
                "consumer_id": "consumer_id of account the login belongs to",
                "consumer_name": "name of the account the login belongs to",
                "created_at": creation_unixtimestamp,
                "id": "internal id of the apikey",
                "username": "loopback of the used login for the Basic-Auth"
            }

## Add Login [/newlogin]
### Create a new login for an account [POST]
Creates a new login within the account the apikey belongs to which
is used during the request.

+ Request

    + Headers

            content-type: application/json
            apikey: myapikey

    + Body
    
            {
                "username": "foobar2",
                "password": "mysecretpassword"
            }

+ Response 403

    + Headers

            content-type: application/json

    + Body

            {
                "message": "Invalid authentication credentials"
            }

+ Response 200

    + Headers

            content-type: application/json

    + Body

            {
                "taskid": "d87d4cc9-f88f-4260-be6e-4601baf71927"
            }